# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4edf8ceddda0d23642b791a554a3de9e05f62b2171339e84d3e1e04902c887080151c930b18996bbef57db4dde187775c3f8ed4f7c40e618fbbfb0cfd1cad667

test:
  secret_key_base: fa9840ec25d93d2794285568a5dfdf7827fe8b35730e47455d0a2819e6cf869b5e5316a0d7941112e8a03ef4e443451056f032aa3b4c338ae130ea09a253c377

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
